/* Generated by JSIL v0.7.8 build 22841. See http://jsil.org/ for more information. */ 
/* Generating type stubs only */ 
var $asm05 = JSIL.DeclareAssembly("Microsoft.Xna.Framework.Input.Touch, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553");

JSIL.DeclareNamespace("Microsoft");
JSIL.DeclareNamespace("Microsoft.Xna");
JSIL.DeclareNamespace("Microsoft.Xna.Framework");
JSIL.DeclareNamespace("Microsoft.Xna.Framework.Input");
JSIL.DeclareNamespace("Microsoft.Xna.Framework.Input.Touch");
/* enum Microsoft.Xna.Framework.Input.Touch.GestureType */ 

JSIL.MakeEnum(
  "Microsoft.Xna.Framework.Input.Touch.GestureType", true, {
    None: 0, 
    Tap: 1, 
    DoubleTap: 2, 
    Hold: 4, 
    HorizontalDrag: 8, 
    VerticalDrag: 16, 
    FreeDrag: 32, 
    Pinch: 64, 
    Flick: 128, 
    DragComplete: 256, 
    PinchComplete: 512
  }, true
);

/* struct Microsoft.Xna.Framework.Input.Touch.GestureSample */ 

(function GestureSample$Members () {
  var $, $thisType;
  JSIL.MakeType({
      BaseType: $asm09.TypeRef("System.ValueType"), 
      Name: "Microsoft.Xna.Framework.Input.Touch.GestureSample", 
      IsPublic: true, 
      IsReferenceType: false, 
      MaximumConstructorArguments: 6, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.ExternalMethod({Static:false, Public:true }, ".ctor", 
      new JSIL.MethodSignature(null, [
          $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.GestureType"), $asm09.TypeRef("System.TimeSpan"), 
          $asm01.TypeRef("Microsoft.Xna.Framework.Vector2"), $asm01.TypeRef("Microsoft.Xna.Framework.Vector2"), 
          $asm01.TypeRef("Microsoft.Xna.Framework.Vector2"), $asm01.TypeRef("Microsoft.Xna.Framework.Vector2")
        ], [])
    );

    $.ExternalMethod({Static:false, Public:true }, "get_Delta", 
      new JSIL.MethodSignature($asm01.TypeRef("Microsoft.Xna.Framework.Vector2"), [], [])
    );

    $.ExternalMethod({Static:false, Public:true }, "get_Delta2", 
      new JSIL.MethodSignature($asm01.TypeRef("Microsoft.Xna.Framework.Vector2"), [], [])
    );

    $.ExternalMethod({Static:false, Public:true }, "get_GestureType", 
      new JSIL.MethodSignature($asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.GestureType"), [], [])
    );

    $.ExternalMethod({Static:false, Public:true }, "get_Position", 
      new JSIL.MethodSignature($asm01.TypeRef("Microsoft.Xna.Framework.Vector2"), [], [])
    );

    $.ExternalMethod({Static:false, Public:true }, "get_Position2", 
      new JSIL.MethodSignature($asm01.TypeRef("Microsoft.Xna.Framework.Vector2"), [], [])
    );

    $.ExternalMethod({Static:false, Public:true }, "get_Timestamp", 
      new JSIL.MethodSignature($asm09.TypeRef("System.TimeSpan"), [], [])
    );

    $.Field({Static:false, Public:false}, "_gestureType", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.GestureType")); 
    $.Field({Static:false, Public:false}, "_timestamp", $asm09.TypeRef("System.TimeSpan")); 
    $.Field({Static:false, Public:false}, "_position", $asm01.TypeRef("Microsoft.Xna.Framework.Vector2")); 
    $.Field({Static:false, Public:false}, "_position2", $asm01.TypeRef("Microsoft.Xna.Framework.Vector2")); 
    $.Field({Static:false, Public:false}, "_delta", $asm01.TypeRef("Microsoft.Xna.Framework.Vector2")); 
    $.Field({Static:false, Public:false}, "_delta2", $asm01.TypeRef("Microsoft.Xna.Framework.Vector2")); 
    $.Property({Static:false, Public:true }, "GestureType", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.GestureType"));

    $.Property({Static:false, Public:true }, "Timestamp", $asm09.TypeRef("System.TimeSpan"));

    $.Property({Static:false, Public:true }, "Position", $asm01.TypeRef("Microsoft.Xna.Framework.Vector2"));

    $.Property({Static:false, Public:true }, "Position2", $asm01.TypeRef("Microsoft.Xna.Framework.Vector2"));

    $.Property({Static:false, Public:true }, "Delta", $asm01.TypeRef("Microsoft.Xna.Framework.Vector2"));

    $.Property({Static:false, Public:true }, "Delta2", $asm01.TypeRef("Microsoft.Xna.Framework.Vector2"));

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class Microsoft.Xna.Framework.Input.Touch.Touch */ 

(function Touch$Members () {
  var $, $thisType;
  JSIL.MakeStaticClass("Microsoft.Xna.Framework.Input.Touch.Touch", false, [], function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.ExternalMethod({Static:true , Public:false}, "get_WindowHandle", 
      new JSIL.MethodSignature($asm09.TypeRef("System.IntPtr"), [], [])
    );

    $.ExternalMethod({Static:true , Public:false}, "set_WindowHandle", 
      new JSIL.MethodSignature(null, [$asm09.TypeRef("System.IntPtr")], [])
    );

    $.Field({Static:true , Public:false}, "_windowHandle", $asm09.TypeRef("System.IntPtr")); 
    $.Field({Static:true , Public:false}, "SyncObject", $.Object); 
    $.Property({Static:true , Public:false}, "WindowHandle", $asm09.TypeRef("System.IntPtr"));

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* struct Microsoft.Xna.Framework.Input.Touch.TouchCollection */ 

(function TouchCollection$Members () {
  var $, $thisType;
  JSIL.MakeType({
      BaseType: $asm09.TypeRef("System.ValueType"), 
      Name: "Microsoft.Xna.Framework.Input.Touch.TouchCollection", 
      IsPublic: true, 
      IsReferenceType: false, 
      MaximumConstructorArguments: 1, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.ExternalMethod({Static:false, Public:true }, ".ctor", 
      new JSIL.MethodSignature(null, [$jsilcore.TypeRef("System.Array", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")])], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "Add", 
      new JSIL.MethodSignature(null, [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")], [])
    );

    $.ExternalMethod({Static:false, Public:false}, "AddTouchLocation", 
      new JSIL.MethodSignature(null, [
          $.Int32, $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocationState"), 
          $.Single, $.Single, 
          $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocationState"), $.Single, 
          $.Single
        ], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "Clear", 
      new JSIL.MethodSignature(null, [], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "Contains", 
      new JSIL.MethodSignature($.Boolean, [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "CopyTo", 
      new JSIL.MethodSignature(null, [$jsilcore.TypeRef("System.Array", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")]), $.Int32], [])
    );

    $.ExternalMethod({Static:false, Public:true }, "FindById", 
      new JSIL.MethodSignature($.Boolean, [$.Int32, $jsilcore.TypeRef("JSIL.Reference", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")])], [])
    );

    $.ExternalMethod({Static:true , Public:false}, "FindById", 
      new JSIL.MethodSignature($.Int32, [$jsilcore.TypeRef("JSIL.Reference", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.XNAINPUT_TOUCH_LOCATION_STATE")]), $.Int32], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "get_Count", 
      new JSIL.MethodSignature($.Int32, [], [])
    );

    $.ExternalMethod({Static:false, Public:true }, "get_IsConnected", 
      new JSIL.MethodSignature($.Boolean, [], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "get_IsReadOnly", 
      new JSIL.MethodSignature($.Boolean, [], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "get_Item", 
      new JSIL.MethodSignature($asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation"), [$.Int32], [])
    );

    $.ExternalMethod({Static:false, Public:true }, "GetEnumerator", 
      new JSIL.MethodSignature($asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchCollection/Enumerator"), [], [])
    );

    $.ExternalMethod({Static:true , Public:false}, "GetLocInfo", 
      new JSIL.MethodSignature($.Boolean, [
          $jsilcore.TypeRef("JSIL.Reference", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.XNAINPUT_TOUCH_LOCATION_STATE")]), $.Int32, 
          $jsilcore.TypeRef("JSIL.Reference", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchCollection/LocInfo")])
        ], [])
    );

    $.ExternalMethod({Static:false, Public:false}, "GetPreviousLocation", 
      new JSIL.MethodSignature($.Boolean, [
          $.Int32, $.Int32, 
          $jsilcore.TypeRef("JSIL.Reference", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")])
        ], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "IndexOf", 
      new JSIL.MethodSignature($.Int32, [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "Insert", 
      new JSIL.MethodSignature(null, [$.Int32, $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "Remove", 
      new JSIL.MethodSignature($.Boolean, [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "RemoveAt", 
      new JSIL.MethodSignature(null, [$.Int32], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "set_Item", 
      new JSIL.MethodSignature(null, [$.Int32, $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")], [])
    );

    $.ExternalMethod({Static:false, Public:false, Virtual:true }, "System.Collections.Generic.IEnumerable$lMicrosoft.Xna.Framework.Input.Touch.TouchLocation$g.GetEnumerator", 
      new JSIL.MethodSignature($asm09.TypeRef("System.Collections.Generic.IEnumerator`1", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")]), [], [])
    )
      .Overrides(2, "GetEnumerator");

    $.ExternalMethod({Static:false, Public:false, Virtual:true }, "System.Collections.IEnumerable.GetEnumerator", 
      new JSIL.MethodSignature($asm09.TypeRef("System.Collections.IEnumerator"), [], [])
    )
      .Overrides(3, "GetEnumerator");

    $.ExternalMethod({Static:false, Public:false}, "Update", 
      new JSIL.MethodSignature(null, [
          $jsilcore.TypeRef("JSIL.Reference", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.XNAINPUT_TOUCH_LOCATION_STATE")]), $jsilcore.TypeRef("JSIL.Reference", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.XNAINPUT_TOUCH_LOCATION_STATE")]), 
          $.Boolean
        ], [])
    );

    $.Field({Static:false, Public:false}, "isConnected", $.Boolean); 
    $.Field({Static:false, Public:false}, "locationCount", $.Int32); 
    $.Field({Static:false, Public:false}, "location0", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")); 
    $.Field({Static:false, Public:false}, "location1", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")); 
    $.Field({Static:false, Public:false}, "location2", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")); 
    $.Field({Static:false, Public:false}, "location3", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")); 
    $.Field({Static:false, Public:false}, "location4", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")); 
    $.Field({Static:false, Public:false}, "location5", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")); 
    $.Field({Static:false, Public:false}, "location6", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")); 
    $.Field({Static:false, Public:false}, "location7", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")); 
    $.Field({Static:true , Public:false}, "prevLocations", $jsilcore.TypeRef("System.Array", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")]), function ($pi) {
        return JSIL.Array.New($asm05.Microsoft.Xna.Framework.Input.Touch.TouchLocation, 8);
      }); 
    $.Property({Static:false, Public:true }, "IsConnected", $.Boolean);

    $.Property({Static:false, Public:true , Virtual:true }, "Item", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation"));

    $.Property({Static:false, Public:true , Virtual:true }, "Count", $.Int32);

    $.Property({Static:false, Public:true , Virtual:true }, "IsReadOnly", $.Boolean);

    $.ImplementInterfaces(
      /* 0 */ $asm09.TypeRef("System.Collections.Generic.IList`1", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")]), 
      /* 1 */ $asm09.TypeRef("System.Collections.Generic.ICollection`1", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")]), 
      /* 2 */ $asm09.TypeRef("System.Collections.Generic.IEnumerable`1", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")]), 
      /* 3 */ $asm09.TypeRef("System.Collections.IEnumerable")
    );

    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm09.TypeRef("System.Reflection.DefaultMemberAttribute"), function () { return ["Item"]; });

})();

/* struct Microsoft.Xna.Framework.Input.Touch.TouchCollection/LocInfo */ 

(function LocInfo$Members () {
  var $, $thisType;
  JSIL.MakeType({
      BaseType: $asm09.TypeRef("System.ValueType"), 
      Name: "Microsoft.Xna.Framework.Input.Touch.TouchCollection/LocInfo", 
      IsPublic: false, 
      IsReferenceType: false, 
      MaximumConstructorArguments: 3, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.ExternalMethod({Static:false, Public:true }, ".ctor", 
      new JSIL.MethodSignature(null, [
          $.Int32, $.Single, 
          $.Single
        ], [])
    );

    $.Field({Static:false, Public:true }, "Id", $.Int32); 
    $.Field({Static:false, Public:true }, "X", $.Single); 
    $.Field({Static:false, Public:true }, "Y", $.Single); 
    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* struct Microsoft.Xna.Framework.Input.Touch.TouchCollection/Enumerator */ 

(function Enumerator$Members () {
  var $, $thisType;
  JSIL.MakeType({
      BaseType: $asm09.TypeRef("System.ValueType"), 
      Name: "Microsoft.Xna.Framework.Input.Touch.TouchCollection/Enumerator", 
      IsPublic: false, 
      IsReferenceType: false, 
      MaximumConstructorArguments: 1, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.ExternalMethod({Static:false, Public:false}, ".ctor", 
      new JSIL.MethodSignature(null, [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchCollection")], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "Dispose", 
      new JSIL.MethodSignature(null, [], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "get_Current", 
      new JSIL.MethodSignature($asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation"), [], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "MoveNext", 
      new JSIL.MethodSignature($.Boolean, [], [])
    );

    $.ExternalMethod({Static:false, Public:false, Virtual:true }, "System.Collections.IEnumerator.get_Current", 
      new JSIL.MethodSignature($.Object, [], [])
    )
      .Overrides(2, "get_Current");

    $.ExternalMethod({Static:false, Public:false, Virtual:true }, "System.Collections.IEnumerator.Reset", 
      new JSIL.MethodSignature(null, [], [])
    )
      .Overrides(2, "Reset");

    $.Field({Static:false, Public:false}, "collection", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchCollection")); 
    $.Field({Static:false, Public:false}, "position", $.Int32); 
    $.Property({Static:false, Public:true , Virtual:true }, "Current", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation"));

    $.Property({Static:false, Public:false, Virtual:true }, "System.Collections.IEnumerator.Current", $.Object);

    $.ImplementInterfaces(
      /* 0 */ $asm09.TypeRef("System.Collections.Generic.IEnumerator`1", [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocation")]), 
      /* 1 */ $asm09.TypeRef("System.IDisposable"), 
      /* 2 */ $asm09.TypeRef("System.Collections.IEnumerator")
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* enum Microsoft.Xna.Framework.Input.Touch.TouchLocationState */ 

JSIL.MakeEnum(
  "Microsoft.Xna.Framework.Input.Touch.TouchLocationState", true, {
    Invalid: 0, 
    Released: 1, 
    Pressed: 2, 
    Moved: 3
  }, false
);

/* struct Microsoft.Xna.Framework.Input.Touch.TouchPanelCapabilities */ 

(function TouchPanelCapabilities$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm09.System.Boolean)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm09.System.Int32)) ();
  };

  function TouchPanelCapabilities_get_IsConnected () {
    return this.TouchPanelCapabilities$IsConnected$value;
  };

  function TouchPanelCapabilities_get_MaximumTouchCount () {
    return this.TouchPanelCapabilities$MaximumTouchCount$value;
  };

  function TouchPanelCapabilities_set_IsConnected (value) {
    this.TouchPanelCapabilities$IsConnected$value = value;
  };

  function TouchPanelCapabilities_set_MaximumTouchCount (value) {
    this.TouchPanelCapabilities$MaximumTouchCount$value = value;
  };

  JSIL.MakeType({
      BaseType: $asm09.TypeRef("System.ValueType"), 
      Name: "Microsoft.Xna.Framework.Input.Touch.TouchPanelCapabilities", 
      IsPublic: true, 
      IsReferenceType: false, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, "get_IsConnected", 
      new JSIL.MethodSignature($.Boolean, [], []), 
      TouchPanelCapabilities_get_IsConnected
    )
      .Attribute($asm09.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_MaximumTouchCount", 
      new JSIL.MethodSignature($.Int32, [], []), 
      TouchPanelCapabilities_get_MaximumTouchCount
    )
      .Attribute($asm09.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.ExternalMethod({Static:true , Public:false}, "GetCaps", 
      new JSIL.MethodSignature($.Type, [], [])
    );

    $.Method({Static:false, Public:false}, "set_IsConnected", 
      new JSIL.MethodSignature(null, [$.Boolean], []), 
      TouchPanelCapabilities_set_IsConnected
    )
      .Attribute($asm09.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "set_MaximumTouchCount", 
      new JSIL.MethodSignature(null, [$.Int32], []), 
      TouchPanelCapabilities_set_MaximumTouchCount
    )
      .Attribute($asm09.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Field({Static:false, Public:false}, "TouchPanelCapabilities$IsConnected$value", $.Boolean)
      .Attribute($asm09.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $.Field({Static:false, Public:false}, "TouchPanelCapabilities$MaximumTouchCount$value", $.Int32)
      .Attribute($asm09.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $.Property({Static:false, Public:true }, "IsConnected", $.Boolean);

    $.Property({Static:false, Public:true }, "MaximumTouchCount", $.Int32);

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* struct Microsoft.Xna.Framework.Input.Touch.TouchLocation */ 

(function TouchLocation$Members () {
  var $, $thisType;
  JSIL.MakeType({
      BaseType: $asm09.TypeRef("System.ValueType"), 
      Name: "Microsoft.Xna.Framework.Input.Touch.TouchLocation", 
      IsPublic: true, 
      IsReferenceType: false, 
      MaximumConstructorArguments: 7, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.ExternalMethod({Static:false, Public:true }, ".ctor", 
      new JSIL.MethodSignature(null, [
          $.Int32, $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocationState"), 
          $asm01.TypeRef("Microsoft.Xna.Framework.Vector2")
        ], [])
    );

    $.ExternalMethod({Static:false, Public:true }, ".ctor", 
      new JSIL.MethodSignature(null, [
          $.Int32, $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocationState"), 
          $asm01.TypeRef("Microsoft.Xna.Framework.Vector2"), $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocationState"), 
          $asm01.TypeRef("Microsoft.Xna.Framework.Vector2")
        ], [])
    );

    $.ExternalMethod({Static:false, Public:false}, ".ctor", 
      new JSIL.MethodSignature(null, [
          $.Int32, $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocationState"), 
          $.Single, $.Single, 
          $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocationState"), $.Single, 
          $.Single
        ], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "Equals", 
      new JSIL.MethodSignature($.Boolean, [$.Type], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "Object.Equals", 
      new JSIL.MethodSignature($.Boolean, [$.Object], [])
    );

    $.ExternalMethod({Static:false, Public:true }, "get_Id", 
      new JSIL.MethodSignature($.Int32, [], [])
    );

    $.ExternalMethod({Static:false, Public:true }, "get_Position", 
      new JSIL.MethodSignature($asm01.TypeRef("Microsoft.Xna.Framework.Vector2"), [], [])
    );

    $.ExternalMethod({Static:false, Public:true }, "get_State", 
      new JSIL.MethodSignature($asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocationState"), [], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "GetHashCode", 
      new JSIL.MethodSignature($.Int32, [], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "op_Equality", 
      new JSIL.MethodSignature($.Boolean, [$.Type, $.Type], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "op_Inequality", 
      new JSIL.MethodSignature($.Boolean, [$.Type, $.Type], [])
    );

    $.ExternalMethod({Static:false, Public:true , Virtual:true }, "toString", 
      new JSIL.MethodSignature($.String, [], [])
    );

    $.ExternalMethod({Static:false, Public:true }, "TryGetPreviousLocation", 
      new JSIL.MethodSignature($.Boolean, [$jsilcore.TypeRef("JSIL.Reference", [$.Type])], [])
    );

    $.Field({Static:false, Public:false}, "id", $.Int32); 
    $.Field({Static:false, Public:false}, "state", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocationState")); 
    $.Field({Static:false, Public:false}, "x", $.Single); 
    $.Field({Static:false, Public:false}, "y", $.Single); 
    $.Field({Static:false, Public:false}, "prevState", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocationState")); 
    $.Field({Static:false, Public:false}, "prevX", $.Single); 
    $.Field({Static:false, Public:false}, "prevY", $.Single); 
    $.Property({Static:false, Public:true }, "State", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchLocationState"));

    $.Property({Static:false, Public:true }, "Id", $.Int32);

    $.Property({Static:false, Public:true }, "Position", $asm01.TypeRef("Microsoft.Xna.Framework.Vector2"));

    $.ImplementInterfaces(
      /* 0 */ $asm09.TypeRef("System.IEquatable`1", [$.Type])
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class Microsoft.Xna.Framework.Input.Touch.TouchPanel */ 

(function TouchPanel$Members () {
  var $, $thisType;
  JSIL.MakeStaticClass("Microsoft.Xna.Framework.Input.Touch.TouchPanel", true, [], function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.ExternalMethod({Static:true , Public:true }, "get_DisplayHeight", 
      new JSIL.MethodSignature($.Int32, [], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "get_DisplayOrientation", 
      new JSIL.MethodSignature($asm01.TypeRef("Microsoft.Xna.Framework.DisplayOrientation"), [], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "get_DisplayWidth", 
      new JSIL.MethodSignature($.Int32, [], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "get_EnabledGestures", 
      new JSIL.MethodSignature($asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.GestureType"), [], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "get_IsGestureAvailable", 
      new JSIL.MethodSignature($.Boolean, [], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "get_WindowHandle", 
      new JSIL.MethodSignature($asm09.TypeRef("System.IntPtr"), [], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "GetCapabilities", 
      new JSIL.MethodSignature($asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchPanelCapabilities"), [], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "GetState", 
      new JSIL.MethodSignature($asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchCollection"), [], [])
    );

    $.ExternalMethod({Static:true , Public:false}, "OnDisplaySettingsChanged", 
      new JSIL.MethodSignature(null, [], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "ReadGesture", 
      new JSIL.MethodSignature($asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.GestureSample"), [], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "set_DisplayHeight", 
      new JSIL.MethodSignature(null, [$.Int32], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "set_DisplayOrientation", 
      new JSIL.MethodSignature(null, [$asm01.TypeRef("Microsoft.Xna.Framework.DisplayOrientation")], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "set_DisplayWidth", 
      new JSIL.MethodSignature(null, [$.Int32], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "set_EnabledGestures", 
      new JSIL.MethodSignature(null, [$asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.GestureType")], [])
    );

    $.ExternalMethod({Static:true , Public:true }, "set_WindowHandle", 
      new JSIL.MethodSignature(null, [$asm09.TypeRef("System.IntPtr")], [])
    );

    $.Constant({Static:true , Public:false}, "AllGestureTypes", 1023); 
    $.Field({Static:true , Public:false}, "nointerop", $.Boolean, false); 
    $.Field({Static:true , Public:false}, "prevState", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.XNAINPUT_TOUCH_LOCATION_STATE")); 
    $.Field({Static:true , Public:false}, "touchState", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.TouchCollection")); 
    $.Field({Static:true , Public:false}, "displayOrientation", $asm01.TypeRef("Microsoft.Xna.Framework.DisplayOrientation")); 
    $.Field({Static:true , Public:false}, "displayWidth", $.Int32); 
    $.Field({Static:true , Public:false}, "displayHeight", $.Int32); 
    $.Field({Static:true , Public:false}, "displaySettingsChanged", $.Boolean); 
    $.Field({Static:true , Public:false}, "_enabledGestures", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.GestureType")); 
    $.Field({Static:true , Public:false}, "_haveGestureBeenEnabled", $.Boolean); 
    function TouchPanel__cctor () {
      $thisType.prevState = new $asm05.Microsoft.Xna.Framework.Input.Touch.XNAINPUT_TOUCH_LOCATION_STATE();
      $thisType.touchState = new $asm05.Microsoft.Xna.Framework.Input.Touch.TouchCollection();
    };


    $.Method({Static:true , Public:false}, ".cctor", 
      new JSIL.MethodSignature(null, [], []), 
      TouchPanel__cctor
    );

    $.Property({Static:true , Public:true }, "EnabledGestures", $asm05.TypeRef("Microsoft.Xna.Framework.Input.Touch.GestureType"));

    $.Property({Static:true , Public:true }, "IsGestureAvailable", $.Boolean);

    $.Property({Static:true , Public:true }, "WindowHandle", $asm09.TypeRef("System.IntPtr"));

    $.Property({Static:true , Public:true }, "DisplayOrientation", $asm01.TypeRef("Microsoft.Xna.Framework.DisplayOrientation"));

    $.Property({Static:true , Public:true }, "DisplayWidth", $.Int32);

    $.Property({Static:true , Public:true }, "DisplayHeight", $.Int32);

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* struct Microsoft.Xna.Framework.Input.Touch.XNAINPUT_TOUCH_LOCATION_STATE */ 

(function XNAINPUT_TOUCH_LOCATION_STATE$Members () {
  var $, $thisType;
  JSIL.MakeType({
      BaseType: $asm09.TypeRef("System.ValueType"), 
      Name: "Microsoft.Xna.Framework.Input.Touch.XNAINPUT_TOUCH_LOCATION_STATE", 
      IsPublic: false, 
      IsReferenceType: false, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Field({Static:false, Public:true }, "Count", $.Int32); 
    $.Field({Static:false, Public:true }, "Id0", $.Int32); 
    $.Field({Static:false, Public:true }, "Id1", $.Int32); 
    $.Field({Static:false, Public:true }, "Id2", $.Int32); 
    $.Field({Static:false, Public:true }, "Id3", $.Int32); 
    $.Field({Static:false, Public:true }, "X0", $.Single); 
    $.Field({Static:false, Public:true }, "Y0", $.Single); 
    $.Field({Static:false, Public:true }, "X1", $.Single); 
    $.Field({Static:false, Public:true }, "Y1", $.Single); 
    $.Field({Static:false, Public:true }, "X2", $.Single); 
    $.Field({Static:false, Public:true }, "Y2", $.Single); 
    $.Field({Static:false, Public:true }, "X3", $.Single); 
    $.Field({Static:false, Public:true }, "Y3", $.Single); 
    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

